// generated by Fast Light User Interface Designer (fluid) version 1.0101

#ifndef Fl_Help_Dialog_H
#define Fl_Help_Dialog_H
#include <fltk/DoubleBufferWindow.h>
#include <fltk/HelpView.h>
#include <fltk/Button.h>

namespace fltk {

class FL_IMAGES_API HelpDialog {
  int index_;
  int max_;
  int line_[100];
  char file_[100][256];
public:
  HelpDialog ();
private:
  DoubleBufferWindow * window_;
  HelpView *view_;
  void cb_view__i (HelpView *, void *);
  static void cb_view_ (HelpView *, void *);
  void cb_Close_i (Button *, void *);
  static void cb_Close (Button *, void *);
  Button *back_;
  void cb_back__i (Button *, void *);
  static void cb_back_ (Button *, void *);
  Button *forward_;
  void cb_forward__i (Button *, void *);
  static void cb_forward_ (Button *, void *);
  Button *smaller_;
  void cb_smaller__i (Button *, void *);
  static void cb_smaller_ (Button *, void *);
  Button *larger_;
  void cb_larger__i (Button *, void *);
  static void cb_larger_ (Button *, void *);
public:
  ~HelpDialog ();
  int h ();
  void hide ();
  void load (const char *f);
  void position (int xx, int yy);
  void resize (int xx, int yy, int ww, int hh);
  void show ();
  void show (int argc, char **argv);
  void textsize (int s);
  int textsize ();
  void topline (const char *n);
  void topline (int n);
  int visible ();
  int w ();
  int x ();
  int y ();
};
 
} // namespace fltk

#endif
