// generated by Fast Light User Interface Designer (fluid) version 2.0100

#include "alignment_panel.h"
#include "FluidType.h"

fltk::Window* alignment_window;

fltk::Input* horizontal_input;

fltk::Input* vertical_input;

fltk::Input* snap_input;

fltk::CheckButton* openlast_button;

static void cb_openlast_button(fltk::CheckButton*, void*) {
  fluid_prefs.set("open_previous_file", openlast_button->value());
}

fltk::CheckButton* prevpos_button;

static void cb_prevpos_button(fltk::CheckButton*, void*) {
  fluid_prefs.set("prev_window_pos", prevpos_button->value());
}

fltk::Input* header_file_input;

fltk::Input* code_file_input;

fltk::CheckButton* include_H_from_C_button;

static void cb_Close(fltk::Button*, void*) {
  alignment_window->hide();
}

fltk::Window* make_alignment_window() {
  fltk::Window* w;
   {fltk::Window* o = alignment_window = new fltk::Window(374, 280, "fluid Preferences");
    w = o;
    o->begin();
     {fltk::Group* o = new fltk::Group(17, 19, 339, 110, "Alignment:");
      o->box(fltk::ENGRAVED_BOX);
      o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
      o->begin();
       {fltk::Input* o = horizontal_input = new fltk::Input(67, 10, 100, 22, "Horizontal:");
        o->callback((fltk::Callback*)alignment_cb, (void*)(1));
        o->when(fltk::WHEN_RELEASE|fltk::WHEN_ENTER_KEY);
      }
       {fltk::Input* o = vertical_input = new fltk::Input(230, 10, 100, 22, "Vertical:");
        o->callback((fltk::Callback*)alignment_cb, (void*)(2));
        o->when(fltk::WHEN_RELEASE|fltk::WHEN_ENTER_KEY);
      }
       {fltk::Input* o = snap_input = new fltk::Input(230, 38, 100, 22, "Snap:");
        o->callback((fltk::Callback*)alignment_cb, (void*)(3));
        o->when(fltk::WHEN_RELEASE|fltk::WHEN_ENTER_KEY);
      }
       {fltk::CheckButton* o = openlast_button = new fltk::CheckButton(3, 59, 193, 25, "Open Previous File on Startup");
        o->callback((fltk::Callback*)cb_openlast_button);
        int b;
        fluid_prefs.get("open_previous_file", b, 0);
        openlast_button->value(b);
      }
       {fltk::CheckButton* o = prevpos_button = new fltk::CheckButton(3, 84, 193, 25, "Remember Window Positions");
        o->callback((fltk::Callback*)cb_prevpos_button);
        int b;
        fluid_prefs.get("prev_window_pos", b, 1);
        prevpos_button->value(b);
      }
      o->end();
    }
     {fltk::Group* o = new fltk::Group(17, 145, 339, 87, "Output File Names:");
      o->box(fltk::ENGRAVED_BOX);
      o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
      o->begin();
       {fltk::Widget* o = new fltk::Widget(6, 7, 323, 25, "Use \"name.ext\" to set name or just \".ext\" to set only extension.");
        o->box(fltk::NO_BOX);
        o->labelsize(11);
        o->align(fltk::ALIGN_LEFT|fltk::ALIGN_CENTER|fltk::ALIGN_INSIDE|fltk::ALIGN_WRAP);
      }
       {fltk::Input* o = header_file_input = new fltk::Input(86, 37, 90, 22, "Header File:");
        o->callback((fltk::Callback*)header_input_cb, (void*)(1));
        o->when(fltk::WHEN_CHANGED);
      }
       {fltk::Input* o = code_file_input = new fltk::Input(239, 37, 90, 22, "Code File:");
        o->callback((fltk::Callback*)code_input_cb, (void*)(1));
        o->when(fltk::WHEN_CHANGED);
      }
       {fltk::CheckButton* o = include_H_from_C_button = new fltk::CheckButton(6, 63, 170, 22, "#include \"header\" in code");
        o->set_flag(fltk::VALUE);
        o->callback((fltk::Callback*)include_H_from_C_button_cb);
      }
      o->end();
    }
     {fltk::Button* o = new fltk::Button(249, 244, 107, 20, "Close");
      o->callback((fltk::Callback*)cb_Close);
    }
    o->end();
    o->set_non_modal();
    o->resizable(o);
  }
  return  w;
}
