// generated by Fast Light User Interface Designer (fluid) version 2.0001

#ifndef coding_style_h
#define coding_style_h
#include <fltk/Fl.h>
extern int gbrace_style;
extern int gno_space_parens;
extern int gbrace_functions;
extern int gindent_tabs;
extern int gtab_size;
extern int galways_return_parens;
extern int gindent_code;
extern void save_coding_style();
extern void write_code_block(char *pBlock);
extern void load_coding_style();
extern const char *get_opening_brace(int is_function);
extern const char *get_indent_string(int level);
extern void show_coding_style_cb(Fl_Widget *, void *);
#include <fltk/Fl_Window.h>
#include <fltk/Fl_Tabs.h>
#include <fltk/Fl_Group.h>
#include <fltk/Fl_Box.h>
#include <fltk/Fl_Round_Button.h>
#include <fltk/Fl_Check_Button.h>
#include <fltk/Fl_Value_Input.h>
#include <fltk/Fl_Button.h>
Fl_Window* make_codingstyle_window();
void load_codingstyle_window();
#endif
