// generated by Fast Light User Interface Designer (fluid) version 0.99

#include <FL/Fl.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Window.H>
extern Fl_Window *image_file_window;
extern Fl_Input *image_filename_input;
extern Fl_Light_Button *include_datas_in_code_button;
extern Fl_Light_Button *tiled_button;
Fl_Window* make_images_dir_window();
extern Fl_Window *images_dir_window;
extern Fl_Input *images_dir_input;
