// generated by Fast Light User Interface Designer (fluid) version 0.99
#include <fltk/Fl.h>
#include <fltk/Fl_Button.h>
#include <fltk/Fl_Input.h>
#include <fltk/Fl_Window.h>
extern void key_cb(Fl_Button*, void*);
extern void shift_cb(Fl_Button*, void*);
Fl_Window *make_window();
