//
// "$Id$"
//
// FLUID template support for the Fast Light Tool Kit (FLTK).
//
// Copyright 1998-2010 by Bill Spitzak and others.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
// USA.
//
// Please report all bugs and problems on the following page:
//
//     http://www.fltk.org/str.php
//

// generated by Fast Light User Interface Designer (fluid) version 3.0000

#ifndef template_panel_h
#define template_panel_h
#include <fltk3/run.h>
#include <fltk3/DoubleWindow.h>
extern fltk3::DoubleWindow *template_panel;
#include <fltk3/Browser.h>
extern fltk3::Browser *template_browser;
#include <fltk3/Box.h>
extern fltk3::Box *template_preview;
#include <fltk3/Input.h>
extern fltk3::Input *template_name;
extern fltk3::Input *template_instance;
#include <fltk3/Group.h>
#include <fltk3/Button.h>
extern fltk3::Button *template_delete;
#include <fltk3/ReturnButton.h>
extern fltk3::ReturnButton *template_submit;
fltk3::DoubleWindow* make_template_panel();
void template_clear();
void template_delete_cb(fltk3::Button *, void *);
void template_load();
#endif

//
// End of "$Id$".
//
