//
// "$Id$"
//
// Workspace Panels for the Fast Light Tool Kit (FLTK).
//
// Copyright 1998-2011 by Bill Spitzak and others.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Library General Public
// License as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
// USA.
//
// Please report all bugs and problems to "fltk-bugs@fltk.org".
//

// generated by Fast Light User Interface Designer (fluid) version 3.0000

#ifndef workspace_panel_h
#define workspace_panel_h
#include <fltk3/run.h>
#include "Fl_Type.h"
#include <fltk3/Pixmap.h>
#include <fltk3/MultiLabel.h>
extern fltk3::Pixmap menu_none_pixmap;
extern fltk3::Pixmap menu_multi_pixmap;
extern fltk3::Pixmap menu_all_pixmap;
#include <fltk3/Group.h>
#include <fltk3/MenuButton.h>
extern void cb_pMenuAll(fltk3::Menu_*, void*);
#include <fltk3/Box.h>

class Fl_Environment_Choice : public fltk3::Group {
public:
  Fl_Environment_Choice(int X, int Y, int W, int H, const char *L = 0);
protected:
  unsigned int pEnv; 
public:
  enum { ENV_NONE=0, ENV_ALL=0x007f, ENV_ALL_SHELL=0x0003, ENV_MAKE=0x0001, ENV_CMAKE=0x0002, ENV_ALL_VC=0x001c, ENV_VC6=0x0004, ENV_VC2008=0x0008, ENV_VC2010=0x0010, ENV_ALL_XC=0x0060, ENV_XC3=0x0020, ENV_XC4=0x0040 }; 
  fltk3::MenuButton *pEnvMenu;
  static fltk3::MenuItem menu_pEnvMenu[];
  static fltk3::MenuItem *pMenuAll;
private:
  void cb_pMenuAll_i(fltk3::Menu_*, void*);
  static void cb_pMenuAll(fltk3::Menu_*, void*);
public:
  fltk3::Box *pEnvList;
  void value(unsigned int v);
  unsigned int value();
};
#include <fltk3/DoubleWindow.h>
extern fltk3::DoubleWindow *workspace_panel;
#include <fltk3/Input.h>
extern fltk3::Input *pName;
extern Fl_Environment_Choice *pEnv;
#include <fltk3/Button.h>
fltk3::DoubleWindow* show_workspace_panel();
#include <fltk3/Choice.h>
#include <fltk3/Output.h>
fltk3::DoubleWindow* make_app_target_panel();
#endif

//
// End of "$Id$".
//
