// generated by Fast Light User Interface Designer (fluid) version 2.0001

#ifndef image_file_h
#define image_file_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
extern Fl_Window *window;
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Slider.H>
extern Fl_Value_Slider *slider;
#include <FL/Fl_Button.H>
#include <FL/Fl_Bitmap.H>
extern Fl_Window *browser_window;
#include <FL/Fl_Browser.H>
extern Fl_Browser *browser;
extern Fl_Window *image_window;
extern Fl_Box *image_box;
#endif
