// generated by Fast Light User Interface Designer (fluid) version 2.0001

#ifndef inactive_h
#define inactive_h
#include <fltk/Fl.h>
#include <fltk/Fl_Window.h>
#include <fltk/Fl_Group.h>
extern Fl_Group* the_group;
#include <fltk/Fl_Button.h>
#include <fltk/Fl_Check_Button.h>
#include <fltk/Fl_Slider.h>
#include <fltk/Fl_Input.h>
#include <fltk/Fl_Input_Browser.h>
#include <fltk/Fl_Item.h>
#include <fltk/Fl_Box.h>
#include <fltk/Fl_Value_Output.h>
#include <fltk/Fl_Scrollbar.h>
#endif
