// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "keyboard_ui.h"
#include <fltk/events.h>

fltk::Output *key_output=(fltk::Output *)0;

fltk::Output *text_output=(fltk::Output *)0;

fltk::Window* make_window() {
  fltk::Window* w;
   {fltk::Window* o = new fltk::Window(490, 190);
    w = o;
    o->shortcut(0xff1b);
    o->begin();
     {fltk::Output* o = key_output = new fltk::Output(15, 15, 170, 30, "Fl::event_key():");
      o->textfont(fltk::COURIER);
      o->labelsize(10);
      o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
    }
     {fltk::Output* o = text_output = new fltk::Output(195, 15, 190, 30, "Fl::event_text():");
      o->textfont(fltk::COURIER);
      o->labelsize(10);
      o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
    }
     {fltk::Button* o = new fltk::Button(15, 50, 20, 20, "Esc ");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::EscapeKey));
    }
     {fltk::Button* o = new fltk::Button(50, 50, 20, 20, "F1");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::F1Key));
    }
     {fltk::Button* o = new fltk::Button(70, 50, 20, 20, "F2");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::F2Key));
    }
     {fltk::Button* o = new fltk::Button(90, 50, 20, 20, "F3");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::F3Key));
    }
     {fltk::Button* o = new fltk::Button(110, 50, 20, 20, "F4");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::F4Key));
    }
     {fltk::Button* o = new fltk::Button(140, 50, 20, 20, "F5");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::F5Key));
    }
     {fltk::Button* o = new fltk::Button(160, 50, 20, 20, "F6");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::F6Key));
    }
     {fltk::Button* o = new fltk::Button(180, 50, 20, 20, "F7");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::F7Key));
    }
     {fltk::Button* o = new fltk::Button(200, 50, 20, 20, "F8");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::F8Key));
    }
     {fltk::Button* o = new fltk::Button(230, 50, 20, 20, "F9");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::F9Key));
    }
     {fltk::Button* o = new fltk::Button(250, 50, 20, 20, "F10");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::F10Key));
    }
     {fltk::Button* o = new fltk::Button(270, 50, 20, 20, "F11");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::F11Key));
    }
     {fltk::Button* o = new fltk::Button(290, 50, 20, 20, "F12");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::F12Key));
    }
     {fltk::Button* o = new fltk::Button(325, 50, 20, 20, "Print ");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::PrintKey));
    }
     {fltk::Button* o = new fltk::Button(345, 50, 20, 20, "Sclk ");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::ScrollLockKey));
    }
     {fltk::Button* o = new fltk::Button(365, 50, 20, 20, "Paus ");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::PauseKey));
    }
     {fltk::Button* o = new fltk::Button(15, 80, 20, 20, "`");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(35, 80, 20, 20, "1");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(55, 80, 20, 20, "2");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(75, 80, 20, 20, "3");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(95, 80, 20, 20, "4");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(115, 80, 20, 20, "5");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(135, 80, 20, 20, "6");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(155, 80, 20, 20, "7");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(175, 80, 20, 20, "8");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(195, 80, 20, 20, "9");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(215, 80, 20, 20, "0");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(235, 80, 20, 20, "-");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(255, 80, 20, 20, "=");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(275, 80, 35, 20, "Bksp");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::BackSpaceKey));
      o->align(fltk::ALIGN_LEFT|fltk::ALIGN_CENTER|fltk::ALIGN_INSIDE);
    }
     {fltk::Button* o = new fltk::Button(325, 80, 20, 20, "Ins ");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::InsertKey));
    }
     {fltk::Button* o = new fltk::Button(345, 80, 20, 20, "Home");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::HomeKey));
    }
     {fltk::Button* o = new fltk::Button(365, 80, 20, 20, "pgup ");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::PageUpKey));
    }
     {fltk::Button* o = new fltk::Button(400, 80, 20, 20, "Num");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::NumLockKey));
    }
     {fltk::Button* o = new fltk::Button(420, 80, 20, 20, "/");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::Keypad+'/'));
    }
     {fltk::Button* o = new fltk::Button(440, 80, 20, 20, "*");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::Keypad+'*'));
    }
     {fltk::Button* o = new fltk::Button(460, 80, 20, 20, "-");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::Keypad+'-'));
    }
     {fltk::Button* o = new fltk::Button(15, 100, 27, 20, "Tab");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::TabKey));
      o->align(fltk::ALIGN_LEFT|fltk::ALIGN_CENTER|fltk::ALIGN_INSIDE);
    }
     {fltk::Button* o = new fltk::Button(42, 100, 20, 20, "Q");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(62, 100, 20, 20, "W");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(82, 100, 20, 20, "E");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(102, 100, 20, 20, "R");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(122, 100, 20, 20, "T");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(142, 100, 20, 20, "Y");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(162, 100, 20, 20, "U");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(182, 100, 20, 20, "I");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(202, 100, 20, 20, "O");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(222, 100, 20, 20, "P");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(242, 100, 20, 20, "[");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(262, 100, 20, 20, "]");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(282, 100, 28, 20, "\\");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
      o->align(fltk::ALIGN_LEFT|fltk::ALIGN_CENTER|fltk::ALIGN_INSIDE);
    }
     {fltk::Button* o = new fltk::Button(325, 100, 20, 20, "Del ");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::DeleteKey));
    }
     {fltk::Button* o = new fltk::Button(345, 100, 20, 20, "End ");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::EndKey));
    }
     {fltk::Button* o = new fltk::Button(365, 100, 20, 20, "pgdn ");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::PageDownKey));
    }
     {fltk::Button* o = new fltk::Button(400, 100, 20, 20, "7");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::Keypad+'7'));
    }
     {fltk::Button* o = new fltk::Button(420, 100, 20, 20, "8");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::Keypad+'8'));
    }
     {fltk::Button* o = new fltk::Button(440, 100, 20, 20, "9");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::Keypad+'9'));
    }
     {fltk::Button* o = new fltk::Button(460, 100, 20, 40, "+");
      o->set_vertical();
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::Keypad+'+'));
      o->align(fltk::ALIGN_TOP|fltk::ALIGN_CENTER|fltk::ALIGN_INSIDE);
    }
     {fltk::Button* o = new fltk::Button(15, 120, 36, 20, "Lock");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::CapsLockKey));
      o->align(fltk::ALIGN_LEFT|fltk::ALIGN_CENTER|fltk::ALIGN_INSIDE);
    }
     {fltk::Button* o = new fltk::Button(51, 120, 20, 20, "A");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(71, 120, 20, 20, "S");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(91, 120, 20, 20, "D");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(111, 120, 20, 20, "F");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(131, 120, 20, 20, "G");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(151, 120, 20, 20, "H");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(171, 120, 20, 20, "J");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(191, 120, 20, 20, "K");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(211, 120, 20, 20, "L");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(231, 120, 20, 20, ";");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(251, 120, 20, 20, "'");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(271, 120, 39, 20, "Enter");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::ReturnKey));
      o->align(fltk::ALIGN_LEFT|fltk::ALIGN_CENTER|fltk::ALIGN_INSIDE);
    }
     {fltk::Button* o = new fltk::Button(400, 120, 20, 20, "4");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::Keypad+'4'));
    }
     {fltk::Button* o = new fltk::Button(420, 120, 20, 20, "5");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::Keypad+'5'));
    }
     {fltk::Button* o = new fltk::Button(440, 120, 20, 20, "6");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::Keypad+'6'));
    }
     {fltk::Button* o = new fltk::Button(15, 140, 45, 20, "Shift");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::LeftShiftKey));
      o->align(fltk::ALIGN_LEFT|fltk::ALIGN_CENTER|fltk::ALIGN_INSIDE);
    }
     {fltk::Button* o = new fltk::Button(60, 140, 20, 20, "Z");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(80, 140, 20, 20, "X");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(100, 140, 20, 20, "C");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(120, 140, 20, 20, "V");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(140, 140, 20, 20, "B");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(160, 140, 20, 20, "N");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(180, 140, 20, 20, "M");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(200, 140, 20, 20, ",");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(220, 140, 20, 20, ".");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(240, 140, 20, 20, "/");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb);
    }
     {fltk::Button* o = new fltk::Button(260, 140, 50, 20, "Shift");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::RightShiftKey));
      o->align(fltk::ALIGN_LEFT|fltk::ALIGN_CENTER|fltk::ALIGN_INSIDE);
    }
     {fltk::Button* o = new fltk::Button(345, 140, 20, 20, "@8->");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::UpKey));
    }
     {fltk::Button* o = new fltk::Button(400, 140, 20, 20, "1");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::Keypad+'1'));
    }
     {fltk::Button* o = new fltk::Button(420, 140, 20, 20, "2");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::Keypad+'2'));
    }
     {fltk::Button* o = new fltk::Button(440, 140, 20, 20, "3");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::Keypad+'3'));
    }
     {fltk::Button* o = new fltk::Button(460, 140, 20, 40);
      o->set_vertical();
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::KeypadEnter));
    }
     {fltk::Button* o = new fltk::Button(15, 160, 30, 20, "Ctrl");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::LeftCtrlKey));
      o->align(fltk::ALIGN_LEFT|fltk::ALIGN_CENTER|fltk::ALIGN_INSIDE);
    }
     {fltk::Button* o = new fltk::Button(45, 160, 30, 20, "Meta");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::LeftMetaKey));
    }
     {fltk::Button* o = new fltk::Button(75, 160, 30, 20, "Alt ");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::LeftAltKey));
    }
     {fltk::Button* o = new fltk::Button(105, 160, 85, 20);
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(' '));
    }
     {fltk::Button* o = new fltk::Button(190, 160, 30, 20, "Alt ");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::RightAltKey));
    }
     {fltk::Button* o = new fltk::Button(220, 160, 30, 20, "Meta");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::RightMetaKey));
    }
     {fltk::Button* o = new fltk::Button(250, 160, 30, 20, "Menu ");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::MenuKey));
    }
     {fltk::Button* o = new fltk::Button(280, 160, 30, 20, "Ctrl");
      o->labelsize(8);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::RightCtrlKey));
      o->align(fltk::ALIGN_LEFT|fltk::ALIGN_CENTER|fltk::ALIGN_INSIDE);
    }
     {fltk::Button* o = new fltk::Button(325, 160, 20, 20, "@4->");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::LeftKey));
    }
     {fltk::Button* o = new fltk::Button(345, 160, 20, 20, "@2->");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::DownKey));
    }
     {fltk::Button* o = new fltk::Button(365, 160, 20, 20, "@6->");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::RightKey));
    }
     {fltk::Button* o = new fltk::Button(400, 160, 40, 20, "0");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::Keypad+'0'));
      o->align(fltk::ALIGN_LEFT|fltk::ALIGN_CENTER|fltk::ALIGN_INSIDE);
    }
     {fltk::Button* o = new fltk::Button(440, 160, 20, 20, ".");
      o->labelsize(10);
      o->callback((fltk::Callback*)key_cb, (void*)(fltk::Keypad+'.'));
    }
     {fltk::Widget* o = new fltk::Widget(400, 15, 80, 40, "Fl::event_state():");
      o->box(fltk::NO_BOX);
      o->labelsize(10);
      o->align(fltk::ALIGN_TOP|fltk::ALIGN_LEFT);
    }
     {fltk::Button* o = new fltk::Button(400, 15, 20, 10, "shift ");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(fltk::SHIFT));
    }
     {fltk::Button* o = new fltk::Button(420, 15, 20, 10, "lock ");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(fltk::CAPSLOCK));
    }
     {fltk::Button* o = new fltk::Button(440, 15, 20, 10, "ctrl");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(fltk::CTRL));
    }
     {fltk::Button* o = new fltk::Button(460, 15, 20, 10, "alt");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(fltk::ALT));
    }
     {fltk::Button* o = new fltk::Button(400, 25, 20, 10, "num");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(fltk::NUMLOCK));
    }
     {fltk::Button* o = new fltk::Button(420, 25, 20, 10, "?");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(0x20));
    }
     {fltk::Button* o = new fltk::Button(440, 25, 20, 10, "meta");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(fltk::META));
    }
     {fltk::Button* o = new fltk::Button(460, 25, 20, 10, "sclk");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(fltk::SCROLLLOCK));
    }
     {fltk::Button* o = new fltk::Button(400, 35, 20, 10, "b1");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(fltk::BUTTON1));
    }
     {fltk::Button* o = new fltk::Button(420, 35, 20, 10, "b2");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(fltk::BUTTON2));
    }
     {fltk::Button* o = new fltk::Button(440, 35, 20, 10, "b3");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(fltk::BUTTON3));
    }
     {fltk::Button* o = new fltk::Button(460, 35, 20, 10, "?");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(0x800));
    }
     {fltk::Button* o = new fltk::Button(400, 45, 20, 10, "?");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(0x1000));
    }
     {fltk::Button* o = new fltk::Button(420, 45, 20, 10, "?");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(0x2000));
    }
     {fltk::Button* o = new fltk::Button(440, 45, 20, 10, "?");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(0x4000));
    }
     {fltk::Button* o = new fltk::Button(460, 45, 20, 10, "?");
      o->selection_color((fltk::Color)3);
      o->labelsize(8);
      o->callback((fltk::Callback*)shift_cb, (void*)(0x8000));
    }
    o->end();
    o->shortcut(0);
    o->resizable(o);
  }
  return  w;
}
