// generated by Fast Light User Interface Designer (fluid) version 2.0001

#ifndef mandelbrot_ui_h
#define mandelbrot_ui_h
#include <fltk/Fl.h>
#include "mandelbrot.h"
#include <fltk/Fl_Window.h>
#include <fltk/Fl_Input.h>
#include <fltk/Fl_Slider.h>
#include <fltk/Fl_Box.h>

class Drawing_Window  {
public:
  void make_window();
  Fl_Window *window;
    Drawing_Area *d;
    Fl_Input *x_input;
private:
    inline void cb_x_input_i(Fl_Input*, void*);
    static void cb_x_input(Fl_Input*, void*);
public:
    Fl_Input *y_input;
private:
    inline void cb_y_input_i(Fl_Input*, void*);
    static void cb_y_input(Fl_Input*, void*);
public:
    Fl_Input *w_input;
private:
    inline void cb_w_input_i(Fl_Input*, void*);
    static void cb_w_input(Fl_Input*, void*);
    inline void cb_brightness_i(Fl_Slider*, void*);
    static void cb_brightness(Fl_Slider*, void*);
    inline void cb_iterations_i(Fl_Slider*, void*);
    static void cb_iterations(Fl_Slider*, void*);
public:
  void update_label();
};
#endif
