// generated by Fast Light User Interface Designer (fluid) version 2.0001

#ifndef radio_h
#define radio_h
#include <fltk/Fl.h>
#include <fltk/Fl_Window.h>
#include <fltk/Fl_Button.h>
#include <fltk/Fl_Return_Button.h>
#include <fltk/Fl_Light_Button.h>
#include <fltk/Fl_Check_Button.h>
#include <fltk/Fl_Round_Button.h>
#include <fltk/Fl_Group.h>
#include <fltk/Fl_Tooltip.h>
extern Fl_Light_Button* ttlb;
#endif
