// generated by Fast Light User Interface Designer (fluid) version 2.00

#ifndef style_ui_h
#define style_ui_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <stdlib.h>
#include <FL/Fl_Input.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *check1;
#include <FL/Fl_Browser.H>
extern Fl_Browser *browser;
#include <FL/Fl_Slider.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Button.H>
extern Fl_Button *cancel_button;
Fl_Window* make_window();
extern Fl_Menu_Item menu_[];
#endif
