// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef tabs_h
#define tabs_h
#include <fltk/Window.h>
extern fltk::Window* foo_window;
#include <fltk/TabGroup.h>
#include <fltk/Group.h>
#include <fltk/Input.h>
#include <fltk/WordwrapInput.h>
#include <fltk/Button.h>
#include <fltk/Clock.h>
#include <stdlib.h>
#include <fltk/ReturnButton.h>
#endif
