// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef resize_h
#define resize_h
void warp(int dx, int dy);
#include <fltk/Window.h>
#include <fltk/Button.h>
#include <fltk/InvisibleBox.h>
#endif
